const routes = {
  '/': 'Home',
  '/dashboard': 'Dashboard',
  '/components': 'Components',
  '/charts': 'Charts',
  '/components/buttons': 'Buttons',
  '/components/social-buttons': 'Social Buttons',
  '/components/cards': 'Cards',
  '/components/forms': 'Forms',
  '/components/modals': 'Modals',
  '/components/switches': 'Switches',
  '/components/tables': 'Tables',
  '/components/tabs': 'Tabs',
  '/forms': 'Forms',
  '/forms/basic-forms': 'Basic Forms',
  '/forms/advanced-forms': 'Advanced Forms',
  '/editors': 'Editors',
  '/editors/text-editors': 'Text Editors',
  '/editors/code-editors': 'Code Editors',
  '/icons': 'Icons',
  '/icons/font-awesome': 'Font Awesome',
  '/icons/simple-line-icons': 'Simple Line Icons',
  '/plugins': 'Plugins',
  '/plugins/calendar': 'Calendar',
  '/plugins/datatable': 'Data Table',
  '/plugins/loading-buttons': 'Loading Buttons',
  '/plugins/notifications': 'Notifications',
  '/plugins/spinners': 'Spinners',
  '/widgets': 'Widgets',
  '/google-maps': 'Google Maps',
  '/ui-kits': 'UI Kits',
  '/ui-kits/invoicing': 'Invoicing',
  '/ui-kits/invoicing/invoice': 'Invoice',
  '/ui-kits/email/compose': 'Compose',
  '/ui-kits/email/inbox': 'Inbox',
  '/ui-kits/email/message': 'Message'
};
export default routes;
